In [1]:
import pandas as pd
import numpy as np

print('import successful...')

import successful...


In [2]:
pd.__version__

'2.3.3'

In [3]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.shape[0]

10000

In [4]:
df.columns.unique()

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='object')

In [5]:
len(df.fuel_type.unique())

3

In [6]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df['fuel_efficiency_mpg'][df['origin'] == 'Asia'].max()

np.float64(41.2)

In [8]:
df.horsepower.median()

np.float64(254.0)

In [9]:
df.horsepower.value_counts().values[[0]]

array([174])

In [10]:
prev_hp = df.horsepower.value_counts()
prev_hp_count = list(df.horsepower.value_counts())
print(prev_hp_count)

[174, 168, 168, 165, 165, 162, 160, 160, 160, 159, 157, 155, 148, 147, 147, 146, 143, 142, 141, 140, 140, 139, 137, 137, 137, 136, 133, 133, 131, 129, 129, 128, 127, 127, 126, 124, 120, 113, 112, 111, 109, 104, 100, 99, 98, 96, 95, 94, 91, 91, 90, 88, 85, 85, 83, 77, 76, 74, 74, 70, 68, 65, 64, 62, 57, 54, 50, 48, 47, 44, 43, 41, 40, 39, 39, 37, 35, 34, 34, 34, 33, 33, 32, 31, 31, 30, 26, 26, 25, 24, 24, 22, 21, 21, 19, 18, 18, 18, 15, 15, 15, 13, 12, 12, 12, 12, 11, 9, 9, 8, 8, 8, 8, 7, 6, 6, 6, 6, 5, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [11]:
fill_val = prev_hp_count[0]

In [12]:
df_copy = df.copy()
df_copy.horsepower.fillna(fill_val, inplace=True)
df_copy.horsepower.median()

np.float64(252.0)

In [13]:
df_copy.horsepower.median()

np.float64(252.0)

In [14]:
df_asia = df[df['origin'] == 'Asia']

In [15]:
df_asia_features = df_asia[['vehicle_weight','model_year']]

In [16]:
df_asia_features.head(7)

,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
16,4750,2021
22,4450,2019


In [17]:
X = df_asia_features.head(7).values
XTX = np.dot(X.T, X)

In [21]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [18]:
# invert XTX
XTX_inv = np.linalg.inv(XTX)

In [19]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [ ]:
w = np.dot(np.dot(XTX_inv, X.T), y)
w.sum()



np.float64(0.36919696904925486)